name: Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Ou outra branch que deseja monitorar
  release:
    types: [created]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar MSBuild e NuGet
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restaurar dependências com NuGet
        run: nuget restore MeuProjeto.sln

      - name: Compilar com MSBuild
        run: msbuild MeuProjeto.sln /p:Configuration=Release

      - name: Criar pacote NuGet
        run: nuget pack MeuProjeto.csproj -OutputDirectory nupkg

      - name: Publicar no GitHub Packages
        run: nuget push nupkg/*.nupkg -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/" -ApiKey ${{ secrets.GITHUB_TOKEN }} -SkipDuplicate
